name: $name
version: $version
main: de.groodian.hyperiorcore.main.Main
description: $description
load: STARTUP
authors:
  - $author
api-version: $apiVersion

commands:
  hyperiorranks:
    description: Set, remove and see ranks
    aliases: [ hr, ranks ]
  help:
    description: Help
    aliases: [ hilfe, h ]
