name: HyperiorCore_by_Groodian
version: 4.5.3
author: Groodian
main: de.groodian.hyperiorcore.main.Main

commands:
  hyperiorranks:
    description: Set, remove and see ranks
    aliases: [ hr, ranks ]